### PR TITLE
Add openssh-client package

### PR DESCRIPTION
**Pull request by tuxpeople**
To use Bastion as a jump host and being able to connect to another SSH enabled device.

### CODE REVIEW

**Comment by neochrome** [comment]
Looks good!
Just a thought - is the ssh client package needed if you're using the `ProxyJump` directive (or `-J` CLI option) to make the jump?

**Comment by tuxpeople** [comment]
Actually, no. It's not needed if you use ```ProxyJump```. It's only needed if you ssh into bastion first and then ssh to another host. In my use case, it's my SSH Client on the iPad which doesn't support "fancy" configuration :-D

**Comment by neochrome** [comment]
Np - we'll merge this!

**Comment by neochrome** [comment]
New image available @ docker hub: neochrome/bastion:1.4.0

**Pull request merged**
